# Generated by Django 5.0.4 on 2024-04-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantmashinesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='mashine',
            field=models.ForeignKey(help_text='Mашина', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.mashine'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='mashine_downtime',
            field=models.TextField(help_text='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='operating_time',
            field=models.FloatField(help_text='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='recovery_date',
            field=models.DateField(help_text='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='recovery_method',
            field=models.ForeignKey(help_text='Способ восстановления', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.recoverymethod'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='refusal_date',
            field=models.DateField(help_text='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='refusal_description',
            field=models.TextField(help_text='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='refusal_node',
            field=models.ForeignKey(help_text='Узел отказа', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.refusalnode'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(help_text='Cервисная компания', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.servicecompany'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='spare_parts_used',
            field=models.TextField(help_text='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='maintence_date',
            field=models.DateField(help_text='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='maintence_type',
            field=models.ForeignKey(help_text='Вид ТО', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.maintenancetype'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='mashine',
            field=models.ForeignKey(help_text='Машина', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.mashine'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='operating_time',
            field=models.IntegerField(help_text='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='service_company',
            field=models.ForeignKey(help_text='Сервисная компания', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.servicecompany'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='work_order_date',
            field=models.DateField(help_text='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintence',
            name='work_order_number',
            field=models.TextField(help_text='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='client',
            field=models.TextField(help_text='Клиент'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='consignee',
            field=models.TextField(help_text='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='delivery_address',
            field=models.TextField(help_text='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='drive_axle_model',
            field=models.ForeignKey(help_text='Модель ведущего моста', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.driveaxlemodel'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='engine_model',
            field=models.ForeignKey(help_text='Модель двигателя', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.enginemodel'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='equipment',
            field=models.TextField(help_text='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_drive_axle_number',
            field=models.TextField(help_text='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_engine_number',
            field=models.TextField(help_text='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_mashine_number',
            field=models.TextField(help_text='Зав. № машины', unique=True),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_shipment_date',
            field=models.DateField(help_text='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_steering_axle_number',
            field=models.TextField(help_text='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='factory_transmission_number',
            field=models.TextField(help_text='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='mashine_model',
            field=models.ForeignKey(help_text='Модель техники', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.mashinemodel'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='service_company',
            field=models.ForeignKey(help_text='Сервисная компания', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.servicecompany'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='steering_axle_model',
            field=models.ForeignKey(help_text='Модель управляемого моста', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.steeringaxlemodel'),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='supply_agreement',
            field=models.TextField(blank=True, help_text='Договор поставки №, дата', null=True),
        ),
        migrations.AlterField(
            model_name='mashine',
            name='transmission_model',
            field=models.ForeignKey(help_text='Модель трансмиссии', on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.transmissionmodel'),
        ),
    ]
