# Generated by Django 5.0.4 on 2024-04-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantmashinesapp', '0002_alter_complaints_mashine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='service_company',
            field=models.ForeignKey(help_text='Cервисная компания', null=True, on_delete=django.db.models.deletion.CASCADE, to='silantmashinesapp.servicecompany'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='spare_parts_used',
            field=models.TextField(help_text='Используемые запасные части', null=True),
        ),
    ]
