# Generated by Django 5.0.4 on 2024-04-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantmashinesapp', '0003_alter_complaints_service_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='service_company',
        ),
    ]
