# Generated by Django 5.0.4 on 2024-04-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantmashinesapp', '0006_remove_mashine_client_remove_mashine_service_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintence',
            name='service_company',
        ),
    ]
