# Generated by Django 5.0.4 on 2024-04-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0009_silantclients_silantmanagers_silantservivecompanies_and_more'),
        ('silantmashinesapp', '0007_remove_maintence_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashine',
            name='client',
            field=models.ForeignKey(help_text='Клиент', null=True, on_delete=django.db.models.deletion.CASCADE, to='silantaccountsapp.silantclients'),
        ),
        migrations.AddField(
            model_name='mashine',
            name='service_company',
            field=models.ForeignKey(help_text='Сервисная компания', null=True, on_delete=django.db.models.deletion.CASCADE, to='silantaccountsapp.silantservivecompanies'),
        ),
    ]
