# Generated by Django 5.0.4 on 2024-04-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantmashinesapp', '0008_mashine_client_mashine_service_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCompany',
        ),
    ]
