# Generated by Django 5.0.4 on 2024-04-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silantuser',
            name='session_duration',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
    ]
