# Generated by Django 5.0.4 on 2024-04-14 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0002_alter_silantuser_session_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilantRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('role_access', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='silantuser',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='silantaccountsapp.silantroles'),
        ),
    ]
