# Generated by Django 5.0.4 on 2024-04-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0003_silantroles_silantuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silantuser',
            name='session_token',
        ),
    ]
