# Generated by Django 5.0.4 on 2024-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0004_remove_silantuser_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='silantuser',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
