# Generated by Django 5.0.4 on 2024-04-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0005_silantuser_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silantuser',
            name='company_name',
        ),
    ]
