# Generated by Django 5.0.4 on 2024-04-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0006_remove_silantuser_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silantuser',
            name='role',
        ),
    ]
