# Generated by Django 5.0.4 on 2024-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silantaccountsapp', '0007_remove_silantuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilantRolesAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64)),
                ('role_access', models.JSONField()),
            ],
        ),
    ]
